# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20161129_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'\xe4\xbd\x9c\xe8\x80\x85'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name=b'\xe5\x88\x86\xe9\xa1\x9e'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'\xe6\x96\xb0\xe5\xa2\x9e\xe6\x99\x82\xe9\x96\x93'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=b'', verbose_name=b'\xe5\x85\xa7\xe5\xae\xb9\xe7\xb0\xa1\xe4\xbb\x8b'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'\xe8\xaa\x9e\xe8\xa8\x80'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'\xe5\x90\x8d\xe7\xa8\xb1'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_price',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe5\x8e\x9f\xe5\x83\xb9'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xe5\x94\xae\xe5\x83\xb9'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateTimeField(null=True, verbose_name=b'\xe4\xb8\x8a\xe6\x9e\xb6\xe6\x99\x82\xe9\x96\x93'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'\xe5\x87\xba\xe7\x89\x88\xe7\xa4\xbe'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, b'\xe6\x9c\xaa\xe4\xb8\x8a\xe6\x9e\xb6'), (1, b'\xe4\xb8\x8a\xe6\x9e\xb6\xe4\xb8\xad'), (2, b'\xe5\xb7\xb2\xe4\xb8\x8b\xe6\x9e\xb6')], default=0, verbose_name=b'\xe7\x8b\x80\xe6\x85\x8b'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='books.Tag', verbose_name=b'\xe6\xa8\x99\xe7\xb1\xa4'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'\xe8\xad\xaf\xe8\x80\x85'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x99\x82\xe9\x96\x93'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\x88\x86\xe9\xa1\x9e\xe5\x90\x8d\xe7\xa8\xb1'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'\xe6\xa8\x99\xe7\xb1\xa4\xe5\x90\x8d\xe7\xa8\xb1'),
        ),
    ]
